// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CmdCol: typeof import('./src/components/CodeExec/CmdCol.vue')['default']
    CodeCol: typeof import('./src/components/CodeExec/CodeCol.vue')['default']
    CodeExec: typeof import('./src/components/CodeExec/CodeExec.vue')['default']
    Exception: typeof import('./src/components/Exception.vue')['default']
    LayoutScript: typeof import('./src/components/LayoutScript.vue')['default']
    MainCtrl: typeof import('./src/components/MainCtrl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptEditor: typeof import('./src/components/ScriptEditor.vue')['default']
    Stdout: typeof import('./src/components/Stdout.vue')['default']
    SystemBar: typeof import('./src/components/CodeExec/SystemBar.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBadge: typeof import('vuetify/lib')['VBadge']
    VBottomNavigation: typeof import('vuetify/lib')['VBottomNavigation']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSystemBar: typeof import('vuetify/lib')['VSystemBar']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
