subscription State {
  state {
    globalState
    nthreads
    threads {
      threadId
      tasks {
        taskId
        prompting
        fileName
        lineNo
        fileLines
      }
    }
  }
}
