query Runs {
  history {
    runs {
      edges {
        node {
          runNo
          state
          startedAt
          endedAt
          script
          exception
        }
      }
    }
  }
}
